language: node_js
node_js:
  - "7.4.0"
os:
  - osx
  - linux
cache:
  directories:
    - node_modules
addons:
  apt:
    packages:
      - xvfb
install:
  - npm prune
  - npm install --save-dev spectron
  - npm install -g mocha electron
  - npm install electron
  - npm install
before_install:
 - chmod +x ./script/travis-build.sh
 - ./script/travis-build.sh  