language: node_js
node_js:
  - "7.4.0"
sudo: required
os:
  - osx
  - linux
cache:
  directories:
    - node_modules
addons:
  apt:
    packages:
      - xvfb
install:
  - npm prune
  - npm install --save-dev spectron electron
  - npm install -g mocha
  - npm install
before_script: ./test/script.sh  