language: node_js
node_js:
  - 7
os:
  - osx
  - linux
cache:
  directories:
    - node_modules
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install -g electron electron-mocha
  - npm install
before_install:
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi