language: node_js
dist: trusty
sudo: required
node_js:
  - "7.4.0"
os:
  - osx
  - linux
cache:
  directories:
    - node_modules
addons:
  apt:
    packages:
      - xvfb
install:
  - npm prune
  - npm install --save-dev spectron electron
  - npm install -g mocha
  - npm install
before_install:
 - chmod +x ./script/travis-build.sh
before_script: ./script/travis-build.sh  