language: node_js
node_js:
  - "7.4.0"
os:
  - osx
  - linux
cache:
  directories:
    - node_modules
addons:
  apt:
    packages:
      - xvfb
install:
  - npm prune
  - npm install --save-dev spectron electron
  - npm install -g mocha
  - npm install
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
      sleep 3
    fi