platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 7 x64
  - npm install
  - npm install --save-dev spectron
  - npm install -g mocha electron

build_script:
  - npm test

test: off